config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  # resources :projects
  # resources :courses
  # resources :blogs
  # resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :students
    resources :projects
    resources :courses
    resources :blogs
    get 'dashboard' => 'dashboard#index'
  end
end

app/models/student.rb
class Student < ApplicationRecord
    paginates_per 6
    has_many :blogs
    has_and_belongs_to_many :courses
    has_many :student_projects
    has_many :projects, through: :student_projects
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
    layout 'admin'
    before_action :set_student, only: %i[ show edit update destroy ]
  
    # GET /students or /students.json
    def index
      @q = Student.ransack(params[:q])
      @students = @q.result(distinct: true).page(params[:page])
    end
  
    # GET /students/1 or /students/1.json
    def show
    end
  
    # GET /students/new
    def new
      @student = Student.new
    end
  
    # GET /students/1/edit
    def edit
    end
  
    # POST /students or /students.json
    def create
      @student = Student.new(student_params)
  
      respond_to do |format|
        if @student.save
          format.html { redirect_to admin_student_url(@student), notice: "Student was successfully created." }
          format.json { render :show, status: :created, location: @student }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /students/1 or /students/1.json
    def update
      respond_to do |format|
        if @student.update(student_params)
          format.html { redirect_to admin_student_url(@student), notice: "Student was successfully updated." }
          format.json { render :show, status: :ok, location: @student }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /students/1 or /students/1.json
    def destroy
      @student.destroy
  
      respond_to do |format|
        format.html { redirect_to admin_students_url, notice: "Student was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_student
        @student = Student.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def student_params
        params.require(:student).permit(:first_name, :last_name, :email, :alternate_contact_number,  :permanent_contact_number, :permanent_address, :local_address)
      end
  end
  

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  layout 'admin'
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :alternate_contact_number,  :permanent_contact_number, :permanent_address, :local_address)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/students/_form.html.erb
<%= form_with(model: [:admin, student]) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :permanent_address %>
    <%= form.text_field :permanent_address, class:"form-control" %>
  </div>

    <div class="field">
    <%= form.label :local_address %>
    <%= form.text_field :local_address, class:"form-control" %>
  </div>

  
  <div class="field">
    <%= form.label :alternate_contact_number %>
    <%= form.text_field :alternate_contact_number, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :permanent_contact_number %>
    <%= form.text_field :permanent_contact_number, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/admin/students/edit.html.erb
<div class="card border-1 shadow">
    <div class="card-header d-flex">

        <h1 class="mr-auto mb-0">Editing Student</h1>
               <%= link_to 'Show', admin_student_path(@student), class:"btn btn-secondary p-2 mb-2 mt-2" %> <%= link_to 'Back', admin_students_path, class:"btn btn-dark ml-2 p-2 mb-2 mt-2" %>
    </div>
    <div class="card-body">
        <%= render 'form', student: @student %>
    </div>
    <div class="card-footer">
        <td><%= link_to 'Destroy', admin_student_path(@student), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
    </div>
</div>

app/views/admin/students/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex flex-row justify-content-between mb-3 ">
<h1 class="h1 mb-2 text-gray-800">Students</h1>
<%
=begin%>
 <%= link_to 'New Student', new_admin_student_path, class:"btn btn-primary  p-2 mb-2 mt-2 pl-3 pr-3" %> 
<%
=end%>
</div>

<div class="card shadow">
  <div class="card-header pb-0 d-flex flex-row justify-content-between ">
    <h6 class="mt-2 font-weight-bold text-primary">Student details</h6>
    <%= link_to 'New Student', new_admin_student_path, class:"btn btn-primary mb-1" %>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
        
        <div class="row">
          <div class="col-sm-12 col-md-6">
          </div>
          <div class="col-sm-12 col-md-6">
            <div id="dataTable_filter" class="dataTables_filter">
              <%= search_form_for @q, url: admin_students_url do |f| %>
                  <%= f.label :first_name %>
                  <%= f.search_field :first_name_cont, class:"form-control form-control-sm" %>
               <%= f.submit class:"btn btn-sm btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
              <table class="table table-bordered table-striped dataTable" id="dataTable">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Permanent Address</th>
                    <th>Local Address</th>
                    <th>Permanent Contact number</th>
                    <th>Alternate Contact number</th>
                    <th colspan="3">Email</th>
                  </tr>
                </thead>

                <tbody>
                  <% @students.each do |student| %>
                    <tr>
                    <% name =  student.first_name  + " " +  student.last_name  %>
                      <td><%= link_to name, admin_student_path(student) %></td>
                      <td><%= student.permanent_address %></td>
                      <td><%= student.local_address %></td>
                      <td><%= student.permanent_contact_number %></td>
                      <td><%= student.alternate_contact_number %></td>
                      <td><%= student.email %></td>

                      <td><%= link_to 'Edit', edit_admin_student_path(student) %></td>
                      <td><%= link_to 'Delete', admin_student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12 col-md-6">
            <div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">
              <%= page_entries_info @students, entry_name: 'students' %>
            </div>
          </div>
          <div class="col-sm-12 col-md-6 ">
            <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
              <%= paginate @students %>
            
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/students/new.html.erb
<div class="card border-1 shadow">
    <div class="card-header d-flex">
        <h1 class="mr-auto mb-0">New Student</h1>
        <%= link_to 'Back', admin_students_path, class:"btn btn-secondary p-2 mb-2 mt-2" %>
    </div>
    <div class="card-body">
        <%= render 'form', student: @student %>
    </div>

</div>

app/views/admin/students/show.html.erb
<p id="notice"><%= notice %></p>



<div class="jumbotron shadow">
 <h1 class="display-3"><%= @student.first_name %> <%= @student.last_name %></h1>
  <p class="lead"><%= @student.permanent_address %> | <%= @student.local_address %></p>
  <hr class="my-4">
  <p><%= @student.permanent_contact_number %> | <%= @student.alternate_contact_number %> | <%= @student.email %></p>
  <div class="d-flex flex-row">
    <%= link_to 'Edit', edit_admin_student_path(@student), class:"btn btn-primary " %>
    <%= link_to 'Back', admin_students_path, class:"btn btn-dark ml-3"%>
  </div>
</div>