config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  # resources :projects
  # resources :courses
  # resources :blogs
  # resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :students
    resources :projects
    resources :courses
    resources :blogs
    get 'dashboard' => 'dashboard#index'
  end
end

app/models/project.rb
class Project < ApplicationRecord
    paginates_per 6
    has_many :student_projects
    has_many :students, through: :student_projects
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  layout 'admin'
    before_action :set_project, only: %i[ show edit update destroy ]
  
    # GET /projects or /projects.json
    def index
      @q = Project.ransack(params[:q])
      @projects = @q.result(distinct: true).page(params[:page])
    end
  
    # GET /projects/1 or /projects/1.json
    def show
    end
  
    # GET /projects/new
    def new
      @project = Project.new
    end
  
    # GET /projects/1/edit
    def edit
    end
  
    # POST /projects or /projects.json
    def create
      @project = Project.new(project_params)
  
      respond_to do |format|
        if @project.save
          format.html { redirect_to admin_project_url(@project), notice: "Project was successfully created." }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /projects/1 or /projects/1.json
    def update
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to admin_project_url(@project), notice: "Project was successfully updated." }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /projects/1 or /projects/1.json
    def destroy
      @project.destroy
  
      respond_to do |format|
        format.html { redirect_to admin_projects_url, notice: "Project was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_project
        @project = Project.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def project_params
        params.require(:project).permit(:name, :description)
      end
  end
  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_with(model: [:admin, project]) do |form| %>
   <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<div class="card border-1 shadow">
    <div class="card-header d-flex">

        <h1 class="mr-auto mb-0">Editing Project</h1>
               <%= link_to 'Show', admin_project_path(@project), class:"btn btn-secondary p-2 mb-2 mt-2" %> <%= link_to 'Back', admin_projects_path, class:"btn btn-dark ml-2 p-2 mb-2 mt-2" %>
    </div>
    <div class="card-body">
        <%= render 'form', project: @project %>
    </div>
    <div class="card-footer">
        <td><%= link_to 'Destroy', admin_project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
    </div>
</div>

app/views/admin/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div class="d-flex flex-row justify-content-between mb-3 ">
<h1 class="h1 mb-2 text-gray-800">Projects</h1>
</div>


<div class="card shadow">
  <div class="card-header pb-0 d-flex flex-row justify-content-between ">
    <h6 class="mt-2 font-weight-bold text-primary">Project Details</h6>
    <%= link_to 'New Project', new_admin_project_path, class:"btn btn-primary mb-1" %>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
        <div class="row">
            <div class="col-sm-12 col-md-6">
            </div>
            <div class="col-sm-12 col-md-6">
              <div id="dataTable_filter" class="dataTables_filter">
                <%= search_form_for @q, url: admin_projects_url do |f| %>
                  <%= f.label :name %>
                  <%= f.search_field :name_cont, class:"form-control form-control-sm" %>
               <%= f.submit class:"btn btn-sm btn-primary" %>
              <% end %>
              </div>
            </div>
          </div>

        
        <div class="row">
          <div class="col-sm-12">
            <table class="table table-bordered table-striped dataTable" id="dataTable">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @projects.each do |project| %>
                  <tr>
                    <td><%= link_to project.name, admin_project_path(project) %></td>
                    <td><%= project.description %></td>
                    <td><%= link_to 'Edit', edit_admin_project_path(project) %></td>
                    <td><%= link_to 'Delete', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

         <div class="row">
          <div class="col-sm-12 col-md-6">
            <div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">
              <%= page_entries_info @projects, entry_name: 'students' %>
            </div>
          </div>
          <div class="col-sm-12 col-md-6 ">
            <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
              <%= paginate @projects, window: 2 %>
            
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/projects/new.html.erb
<div class="card border-1 shadow">
    <div class="card-header d-flex">
        <h1 class="mr-auto mb-0">New Project</h1>
        <%= link_to 'Back', admin_projects_path, class:"btn btn-secondary p-2 mb-2 mt-2" %>
    </div>
    <div class="card-body">
        <%= render 'form', project: @project %>
    </div>

</div>

app/views/admin/projects/show.html.erb
<p id="notice"><%= notice %></p>



<div class="jumbotron shadow">
 <h1 class="display-3"><%= @project.name %></h1>
  <p class="lead">project</p>
  <hr class="my-4">
  <p><%= @project.description %></p>
  <div class="d-flex flex-row">
    <%= link_to 'Edit', edit_admin_project_path(@project), class:"btn btn-primary " %>
    <%= link_to 'Back', admin_projects_path, class:"btn btn-dark ml-3"%>
  </div>
</div>